### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by dod38fr** [libtom/libtommath#82]
Hello

Latest version of Rakudo Perl6 (actually moarvm) does not compile on Debian with libtommath 1.0:
```
src/math/bigintops.c:950:13: error: ‘MP_GEN_RANDOM_MAX’ undeclared (first use in this function); did you mean ‘MP_GEN_RANDOM’?
         if (MP_GEN_RANDOM_MAX >= abs(smallint_max)) {
             ^~~~~~~~~~~~~~~~~
             MP_GEN_RANDOM
```

Moarvm is now using libtommath from March 2017 (i.e. commit 8ae5ddf25aa4bb37a7cc98af8c25147f8e404b3d ) as a git submodule. The MP_GEN_RANDOM_MAX macro was added to 

As a Debian packager, I can only use a released version of libtommath. Could you please create a new release so I can package it and fix moarvm build in Debian ?

All the best

**Comment by sjaeckel** [comment]
Next week okay?

**Comment by dod38fr** [comment]
Yes, no problem. 

Thanks

**Comment by sjaeckel** [comment]
https://github.com/libtom/libtommath/releases/tag/v1.0.1-rc1

can you please try the RC1!?

**Comment by sjaeckel** [comment]
https://github.com/libtom/libtommath/releases/tag/v1.0.1-rc2

@buggywhip found some major things, therefore it's already RC2-time...

**Comment by sjaeckel** [comment]
fixed by 5953f62e42b24af93748b1ee5e1d062e242c2546

**Comment by dod38fr** [comment]
And released in Debian/unstable: https://tracker.debian.org/pkg/libtommath

Thanks :-)
