### PR TITLE
WIP: release v1.2.0

### PR DESCRIPTION
**Pull request by sjaeckel**
Changes on the release-branch

Only for review
Not to be merged (via GitHub Web UI ;-) )!

### CODE REVIEW

**Comment by minad** [comment]
Looks good!

**Comment by sjaeckel** [comment]
> You will also merge this to develop I guess?

sure, I will

**Comment by minad** [comment]
Yes, but I would propose to add two macros MP_VERSION and MP_V(maj,min,pat). Then we can compare MP_VERSION>=MP_V(1,2,0) or allow other comparisons. Maybe you have a better name for MP_V, MP_MAKE_VERSION?

**Comment by sjaeckel** [comment]
> Maybe you have a better name for MP_V, MP_MAKE_VERSION?

MP_MAKE_VERSION is good, maybe MP_TO_VERSION?

**Comment by minad** [comment]
Hmm, I think MAKE or MK makes more sense since it is like a constructor. Is there no precedent in other libs, where they did this in a nice way?

**Comment by minad** [comment]
But maybe we shouldn't even provide this. I basically never wrote code which does these version checks. Instead I rather ensure in the build system/package dependencies what is required and that's it. I don't think we should encourage library users to write code such that it compiles for example against 1.2 and 2.0.

**Comment by minad** [comment]
This is different from compiler version checks I think (the gccver checks and so on that we have). These are harder to exchange since they might be baked into the distribution and the system. But switching library versions is much easier.

**Comment by minad** [comment]
Ok, but is there an issue in requiring 1.2 in newest ltc? I think this is even a good thing since it pushes things forward. Everybody knows disasters like python2/3.

**Comment by sjaeckel** [comment]
> Ok, but is there an issue in requiring 1.2 in newest ltc?

not really... and I like the idea

**Comment by minad** [comment]
@nijtmans Other comments regarding the 1.2 release? Did you try to compile tcl with the release/1.2 branch? It would probably be helpful to know if you stumble upon some issues.

**Comment by nijtmans** [comment]
Yes, I updated Tcl 8.6 with the latest changes:

See: [here](https://core.tcl-lang.org/tcl/timeline?r=libtommath-no-stdint.h-for-8.6)

Tomorrow this will be synchronized to GIT, and built with Travis on many platforms. Anyway, I need my own fork, since it's known not to work with VC++ 6.0   ;-)  But you already know that ....

**Comment by nijtmans** [comment]
The Travis build for Tcl failed. Here are the error-messages:
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_div_d.c(47): error C2220: warning treated as error - no 'object' file generated
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_div_d.c(47): warning C4003: not enough arguments for function-like macro invocation 'MP__STRINGIZE'
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_mul.c(15): error C2220: warning treated as error - no 'object' file generated
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_mul.c(15): warning C4003: not enough arguments for function-like macro invocation 'MP__STRINGIZE'
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_mul.c(28): warning C4003: not enough arguments for function-like macro invocation 'MP__STRINGIZE'
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_mul.c(31): warning C4003: not enough arguments for function-like macro invocation 'MP__STRINGIZE'
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_mul.c(34): warning C4003: not enough arguments for function-like macro invocation 'MP__STRINGIZE'
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_mul.c(44): warning C4003: not enough arguments for function-like macro invocation 'MP__STRINGIZE'
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_sqr.c(10): error C2220: warning treated as error - no 'object' file generated
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_sqr.c(10): warning C4003: not enough arguments for function-like macro invocation 'MP__STRINGIZE'
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_sqr.c(13): warning C4003: not enough arguments for function-like macro invocation 'MP__STRINGIZE'
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_sqr.c(16): warning C4003: not enough arguments for function-like macro invocation 'MP__STRINGIZE'
C:\Users\travis\build\tcltk\tcl\win\..\libtommath\bn_mp_sqr.c(20): warning C4003: not enough arguments for function-like macro invocation 'MP__STRINGIZE'

**Comment by sjaeckel** [comment]
> C:\Users\travis\build\tcltk\tcl\win..\libtommath\bn_mp_div_d.c(47): warning C4003: not enough arguments for function-like macro invocation 'MP__STRINGIZE'

4003 is ignored for our MSVC builds, c.f. [makefile.msvc:17](https://github.com/libtom/libtommath/blob/develop/makefile.msvc#L17) added in 672242bd70d2972313e65f6a4b1a689d7ad688b7

**Comment by minad** [comment]
@nijtmans @sjaeckel yes, this is a false positive.

**Comment by nijtmans** [comment]
> @nijtmans @sjaeckel yes, this is a false positive.

Sure, but one easy to fix/work-around.  I prefer not to disable warnings in the Tcl build, just for this... :-(

**Comment by minad** [comment]
I don't think there is an easy fix. I tried quite a while to find a good solution for the MP_HAS macro which works across many compilers. It is probably possible to disable the warning in tcl only for the tommath files, maybe add a pragma to tommath_private? We could even do this in this repository and reeenable the warning in the makefile. Maybe prepare a PR for that?

**Comment by nijtmans** [comment]
Well, I investigated how MP_HAS() works. Smart!!!  Neither I can think of a good solution. So I disabled the C4003 warning in the (interal) Tcl build now.  I agree that it's a MSVC-only problem.

Let's see tomorrow's build, but I'm confident that it works now! That means, it's a GO for me.

Thanks for all the effort regarding the upcoming 1.2.0 release!

**Comment by sjaeckel** [comment]
@dod38fr can you please check the debian build?

**Comment by nijtmans** [comment]
> Let's see tomorrow's build, but I'm confident that it works now! That means, it's a GO for me.

Indeed the Tcl build with libtommath 1.2.0  [passed](https://travis-ci.org/tcltk/tcl/builds/599970870)

**Comment by dod38fr** [comment]
Hi
Package build fails on Debian while processing doc:
```
Found replacement tag for "a != b" on line 1291 which refers to line 15 (delta 12)
1325:Inserting bn_mp_neg.c:0 lines
Found replacement tag for "a != b" on line 1327 which refers to line 10 (delta 11)
1358:Inserting bn_mp_set.c:0 lines
ERROR:  The tag "mp_zero" on line 1360 was not found in the most recently parsed source!
Found replacement tag for "MP_MASK" on line 1362 which refers to line 9 (delta 13)
```

All the best

**Comment by sjaeckel** [comment]
> Package build fails on Debian while processing doc:

I've removed the book now, see also #383

**Comment by minad** [comment]
Also remove the poster? What other kinds of docs are there? I think we only maintain the manual?

**Comment by minad** [comment]
Why does this PR contain so many commits?

**Comment by sjaeckel** [comment]
> Why does this PR contain so many commits?

because I had to change the base branch to master, since develop now conflicts with it.

**Comment by minad** [comment]
In 1.2 it is really still int, so no issue there. But we should update at some point. If builds work as is, I would proceed with the release.

**Comment by sjaeckel** [comment]
@dod38fr can you please re-test?
