### ISSUE TITLE
MS Visual C++  error

### ISSUE THREAD

**Issue by karel-m** [libtom/libtommath#132]
It seems that MSVC (at least visual studio 2008) compiler does not like `#warning` directive
```
.\bn_mp_set_double.c(52) : fatal error C1021: invalid preprocessor command 'warning'
```
this was introduced in #123

**Comment by czurnieden** [comment]
Yepp, my bad (probably?). `#warning` is not really standard and MSVC does not like it.  It wants something like

    #pragma message ( "Some text for warning" )

Sorry.

**Comment by karel-m** [comment]
#pragma message works, thanks
